
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'opencms.java-conventions'
    id 'opencms.testing-conventions'
    id 'opencms.gwt-conventions'
    id 'opencms.ui-conventions'
    id 'opencms.module-packaging'
    id 'opencms.distribution-conventions'
    id 'maven-publish'
    id 'signing'
    id 'io.github.gradle-nexus.publish-plugin' version '2.0.0'
    id 'com.liferay.tlddoc.builder' version '2.0.1'
}

group = "org.opencms"

layout.buildDirectory.set(file(build_directory))


signing {
    useGpgCmd()
}

nexusPublishing {
    repositories {
        sonatype {
            nexusUrl.set(uri("https://ossrh-staging-api.central.sonatype.com/service/local/"))
            snapshotRepositoryUrl.set(uri("https://central.sonatype.com/repository/maven-snapshots/"))
        }
    }
}



// use the same properties file as the OpenCms core does for the version information
// please note that in a Jenkins CI build, this properties file should be dynamically generated
def externalVersionProps = layout.buildDirectory.file("../version.properties").get().asFile
def propFile;
if (externalVersionProps.exists()){
    println "Using external version properties file: $externalVersionProps"
    propFile=externalVersionProps
}else{
    println 'Using internal version properties file'
    propFile=file("$projectDir/src/org/opencms/main/version.properties")
}

Properties vprops = new Properties()
vprops.load(new FileInputStream(propFile))
opencms {
    productVersion = opencms_version ?: vprops['version.number']
    productName = product_name
    javaVersion = JavaVersion.toVersion(java_target_version)
    addJavadoc = !(project.hasProperty('skip_javadoc') && skip_javadoc.toBoolean())
}

version = opencms.productVersion.get()

// flag, indicating if javadoc should be skipped
boolean addJavadoc = opencms.addJavadoc.get()

// alternative variable name for the case where the version variable is used for something else, e.g. javadoc
ext.ocmsVersion = opencms.productVersion.get()

// deal with external modules project
def extModulesProject = findProject(':extmodules')
def hasExtModules = null != extModulesProject
if (hasExtModules) {
    println 'Adding coreproject property to subprojects.'
    subprojects {
        ext.coreproject = ':'
    }
}

// Repositories applied via opencms.java-conventions

if (project.hasProperty('max_heap_size')){
    opencms.maxHeapSize.set(max_heap_size)
}
ext.max_heap_size = opencms.maxHeapSize.get()

// allModuleNames and modulesDistsDir initialized via opencms.module-packaging


// SourceSets applied via opencms.java-conventions

// Configurations applied via opencms.java-conventions

// import dependencies
apply from: 'dependencies.gradle'
if (project.hasProperty('external_directories')){
    dependencies{
        moduleDeps fileTree(dir: external_directories).matching { include '**/lib/*.jar' }
        moduleDeps fileTree(dir: external_directories).matching { include '**/libext/*.jar' }
    }
}

// Eclipse classpath config applied via opencms.java-conventions

wrapper {
    gradleVersion = '7.5.1'
}

// copyDeps tasks applied via opencms.java-conventions

// Task from the java plugin
jar {
    manifest {
        attributes 'Implementation-Title': 'Alkacon OpenCms',
        'Implementation-Version': archiveVersion,
        'Build-Time': new java.util.Date().format("yyyy-MM-dd HH:mm:ss"),
        'OpenCms-Localization': 'en'
    }
    archiveBaseName = 'opencms-core'
    archiveFileName = 'opencms.jar'
    group 'OpenCms core JARs'

    include 'org/opencms/**'
    include 'org/vaadin/risto/**'
    include 'com/**'
    include 'META-INF/**'
    exclude '**/package.html'
    exclude '**/overview.html'
    exclude '**/.gitignore'

    if (externalVersionProps.exists()){
        exclude 'org/opencms/main/version.properties'
        from (layout.buildDirectory.dir("..")){
            include 'version.properties'
            into 'org/opencms/main'
        }
    }

    metaInf {
        from("${projectDir}/webapp/WEB-INF/opencms.tld")
    }

    doLast {
        if (project.hasProperty('tomcat_update_target') && file(tomcat_update_target).exists()){
            println "copying ${layout.buildDirectory.dir("libs").get().file(archiveName).asFile} to ${tomcat_update_target}"
            copy {
                from  layout.buildDirectory.dir("libs").get().file(archiveName).asFile
                into tomcat_update_target
            }
        }
    }
}

// Task from the java plugin
javadoc {
    classpath += sourceSets.gwt.compileClasspath
    doLast {
        copy {
            from  "${projectDir}/doc/javadoc/logos"
            into layout.buildDirectory.dir("docs/javadoc/logos")
        }
    }

    project.configure(options) {
        memberLevel = org.gradle.external.javadoc.JavadocMemberLevel.PROTECTED
        charSet = "UTF-8"
        author="true"
        version="true"
        source= java_target_version
        linkSource="false"
        overview="${sourceSets.main.output.resourcesDir}/org/opencms/main/overview.html"
        docTitle="OpenCms Core API, version $ocmsVersion"
        windowTitle="OpenCms Core API, version $ocmsVersion"
        header = "<script type=\"text/javascript\"> if (window.location.href.indexOf(\"overview-frame\") == -1) { document.write(\"<a id=\\\"brandingLink\\\" target=\\\"_blank\\\" href=\\\"http://www.alkacon.com\\\"><img border=\\\"0\\\" id=\\\"brandingPic\\\" src=\\\"{@docRoot}/logos/Alkacon.svg\\\" /></a>\"); } else { document.write(\"<a id=\\\"brandingLink\\\" target=\\\"_blank\\\" href=\\\"http://www.opencms.com\\\"><img border=\\\"0\\\" id=\\\"brandingPic\\\" src=\\\"{@docRoot}/logos/OpenCms.svg\\\" /></a>\"); }</script>"
        use="true"
    }
}

tasks.register('javadocJar', Jar) {
    dependsOn javadoc
    archiveClassifier = 'javadoc'
    from layout.buildDirectory.dir("docs/javadoc")
    archiveBaseName = 'opencms-core'
}

tasks.register('sourcesJar', Jar) {
    from sourceSets.main.java.srcDirs
    archiveClassifier = 'sources'
    archiveBaseName = 'opencms-core'
}


tasks.register('resourcesJar', Jar) {
    doFirst {
        println '======================================================'
        println "Building Resources Jar"
        println '======================================================'
    }
    archiveBaseName = 'opencms-resources'
    archiveFileName = 'opencms-resources.jar'
    group 'OpenCms core JARs'
    allModuleNames.each{ moduleName ->
        from ("${projectDir}/modules/${moduleName}/static"){
            into "OPENCMS"
        }
    }
    from ("${projectDir}/webapp/workplaceThemes"){
        exclude '**/*.scss'
    }
    from (layout.buildDirectory.dir("workplaceThemes/opencms")){
        into 'VAADIN/themes/opencms'
    }
    from (layout.buildDirectory.dir("workplaceThemes/opencmsFonts")){
        into 'VAADIN/themes/opencms'
    }

    doLast {
        if (project.hasProperty('tomcat_update_target') && file(tomcat_update_target).exists()){
            println "copying ${layout.buildDirectory.dir("libs").get().file(archiveName).asFile} to ${tomcat_update_target}"
            copy {
                from  layout.buildDirectory.dir("libs").get().file(archiveName).asFile
                into tomcat_update_target
            }
        }
    }
}




// Setup tasks applied via opencms.java-conventions

tlddoc {
    source 'webapp/WEB-INF/opencms.tld'
}


tasks.register('tlddocZip', Zip) {
    dependsOn tlddoc
    archiveFileName = 'tld.zip'
    from ("${project.docsDir}/tlddoc/") {
        include '**/*'
    }
    destinationDirectory = file("${project.docsDir}")
}



// Testing logic moved to opencms.testing-conventions.gradle.kts









tasks.register('testGwt', Test) {
    dependsOn compileTestGwtJava
    classpath=sourceSets.testGwt.runtimeClasspath
    classpath += files("${projectDir}/src")
    classpath += files("${projectDir}/src-gwt")
    classpath += files("${projectDir}/test-gwt")
    useJUnit()
    filter {
        includeTestsMatching 'org.opencms.client.test.AllTests'
    }
    scanForTestClasses false
    testClassesDirs = files(sourceSets.testGwt.java.classesDirectory)
    systemProperties['gwt.args'] = "-logLevel WARN -setProperty locale=en"
    systemProperties['java.awt.headless'] = "true"
    maxHeapSize = max_heap_size
    testLogging.showStandardStreams = true
    ignoreFailures true
}

artifacts {
    archives sourcesJar

	if (gradle.startParameter.taskNames.contains("uploadArchives")) {
        // do not include the war if only running the install task, it takes ages to build
        archives war
        archives resourcesJar
    }

    archives setupJar
    archives sourcesJarSetup

    archives modulesJar
    archives sourcesJarModules

    archives gwtJar
    archives sourcesJarGwt

    archives testJar
    archives sourcesJarTest

    tasks.each { task ->
        if (task.name.startsWith("jar_org.opencms.")){
            def moduleName=task.archiveBaseName
            archives task
            if (tasks.hasProperty("sourcesJar_$moduleName")) {
                archives tasks["sourcesJar_$moduleName"]
            }
        }
    }
    // in case the property 'skip_javadoc' is set to 'true', javadoc generation is skipped - this is supposed to speed up build time for CI
    if (addJavadoc) {
        archives javadocJar
        archives javadocJarSetup
        archives javadocJarModules
        archives javadocJarGwt
        archives javadocJarTest
        tasks.each { task ->
            if (task.name.startsWith("jar_org.opencms.")) {
                def moduleName=task.archiveBaseName
                if (tasks.hasProperty("javadocJar_$moduleName")) {
                    archives tasks["javadocJar_$moduleName"]
                }
            }
        }
    }
}


publishing {
    publications { pubs ->
        core(MavenPublication) {
            from components.java
            artifact sourcesJar
            if (addJavadoc) artifact javadocJar
            pom {
                name = product_name
                description = product_description
                packaging 'jar'
                groupId 'org.opencms'
                url = 'http://www.opencms.org'
                scm {
                    url = 'scm:git@github.com:alkacon/opencms-core.git'
                    connection = 'scm:git@github.com:alkacon/opencms-core.git'
                    developerConnection = 'scm:git@github.com:alkacon/opencms-core.git'
                }
                licenses {
                    license {
                        name = 'GNU Lesser General Public License'
                        url = 'http://www.gnu.org/licenses/lgpl.html'
                        distribution = 'repo'
                    }
                }
                organization {
                    name = 'Alkacon Software'
                    url = 'https://www.alkacon.com'
                }
                developers {
                    developer {
                        name = 'Alkacon Software'
                        url = 'https://www.alkacon.com'
                    }
                }
                withXml {
                    // Update dependencies with resolved versions
                    def hasDependencies = !asNode().dependencies.isEmpty()
                    if (hasDependencies) {
                        // for some reason Gradle incorrectly sets the scope to 'runtime' for some dependencies, so we fix it
                        // (if we didn't do this, the dependencies would be missing in dependent projects)
                        asNode().dependencies.'*'.each() { dep ->
                            if (dep.scope.text() == 'runtime' && dep.artifactId.text() in [
                                        'javax.servlet-api',
                                        'javax.servlet.jsp-api'
                                    ]) {
                                println("Correcting scope for dependency ${dep.artifactId.text()}")
                                dep.scope.first().setValue('compile')
                            }
                        }

                        // add additional repositories to search artifacts in
                        def repositoriesNode = asNode().appendNode('repositories')
                        def respositoryNode = repositoriesNode.appendNode('repository')
                        respositoryNode.appendNode('id', 'vaadin-addons');
                        respositoryNode.appendNode('url', 'https://maven.vaadin.com/vaadin-addons');
                        respositoryNode = repositoriesNode.appendNode('repository')
                        respositoryNode.appendNode('id', 'restlet');
                        respositoryNode.appendNode('url', 'https://maven.restlet.org');
                    }
                }
            }
        }
        /*versionMapping {
         usage('api') {
         fromResolutionOf(configurations.distribution)
         }
         usage('runtime') {
         fromResolutionOf(configurations.distribution)
         }
         }*/
        def furtherPubs = [
            "setup" : [
                "artifacts" : addJavadoc ? [
                    setupJar,
                    sourcesJarSetup,
                    javadocJarSetup
                ] : [setupJar, sourcesJarSetup]
            ],
            "modules" : [
                "artifacts" : addJavadoc ? [
                    modulesJar,
                    sourcesJarModules,
                    javadocJarModules
                ] : [
                    modulesJar,
                    sourcesJarModules
                ]
            ],
            "gwt" : [
                "artifacts" : addJavadoc ? [
                    gwtJar,
                    sourcesJarGwt,
                    javadocJarGwt
                ] : [gwtJar, sourcesJarGwt]
            ],
            "test" : [
                "artifacts" : addJavadoc ? [
                    testJar,
                    sourcesJarTest,
                    javadocJarTest
                ] : [testJar, sourcesJarTest]
            ]
        ]
        furtherPubs.each { pub ->
            pubs.create(pub.key, MavenPublication) {
                pub.value.artifacts.each { art ->
                    artifact art
                }
                pom {
                    artifactId "opencms-${pub.key}"
                    name = product_name
                    description = product_description
                    packaging 'jar'
                    groupId 'org.opencms'
                    url = 'http://www.opencms.org'
                    scm {
                        url = 'scm:git@github.com:alkacon/opencms-core.git'
                        connection = 'scm:git@github.com:alkacon/opencms-core.git'
                        developerConnection = 'scm:git@github.com:alkacon/opencms-core.git'
                    }
                    licenses {
                        license {
                            name = 'GNU Lesser General Public License'
                            url = 'http://www.gnu.org/licenses/lgpl.html'
                            distribution = 'repo'
                        }
                    }
                    organization {
                        name = 'Alkacon Software'
                        url = 'https://www.alkacon.com'
                    }
                    developers {
                        developer {
                            name = 'Alkacon Software'
                            url = 'https://www.alkacon.com'
                        }
                    }

                    if (pub.key == 'gwt') {
                        withXml { xml ->
                            def deps = xml.asNode().appendNode('dependencies');
                            def dependenciesGwt=project.configurations.gwtCompile.dependencies
                            dependenciesGwt.each { dep ->
                                if (dep instanceof ExternalModuleDependency) {
                                    def dependency = deps.appendNode('dependency')
                                    dependency.appendNode('groupId', dep.group)
                                    dependency.appendNode('artifactId', dep.name)
                                    dependency.appendNode('version', dep.version)
                                }
                            }
                            def dependencyNode = deps.appendNode('dependency')
                            dependencyNode.appendNode('artifactId','opencms-core')
                            dependencyNode.appendNode('groupId','org.opencms')
                            dependencyNode.appendNode('version',version)
                        }
                    } else {
                        withXml {
                            def hasDependencies = !asNode().dependencies.isEmpty()
                            if (hasDependencies) {
                                asNode().removeChild(asNode().dependencies)
                            }
                            def dependenciesNode = asNode().appendNode('dependencies')
                            def dependencyNode = dependenciesNode.appendNode('dependency')
                            dependencyNode.appendNode('artifactId','opencms-core')
                            dependencyNode.appendNode('groupId','org.opencms')
                            dependencyNode.appendNode('version',version)
                        }
                    }
                }
            }
        }
        if (gradle.startParameter.taskNames.contains("uploadArchives")) {
            webapp(MavenPublication) {
                artifact war
                pom {
                    artifactId 'opencms-webapp'
                    name = product_name
                    description = product_description
                    packaging 'war'
                    groupId 'org.opencms'
                    url = 'http://www.opencms.org'
                    scm {
                        url = 'scm:git@github.com:alkacon/opencms-core.git'
                        connection = 'scm:git@github.com:alkacon/opencms-core.git'
                        developerConnection = 'scm:git@github.com:alkacon/opencms-core.git'
                    }
                    licenses {
                        license {
                            name = 'GNU Lesser General Public License'
                            url = 'http://www.gnu.org/licenses/lgpl.html'
                            distribution = 'repo'
                        }
                    }
                    organization {
                        name = 'Alkacon Software'
                        url = 'https://www.alkacon.com'
                    }
                    developers {
                        developer {
                            name = 'Alkacon Software'
                            url = 'https://www.alkacon.com'
                        }
                    }
                }
            }
            pubs.each { pub ->
                signing.sign pub
            }
        }
    }
}


// add it to keep the old task names
tasks.register('install') {
    dependsOn publishToMavenLocal
    doFirst {
        println "Installing artifacts for version $version"
    }
}

tasks.register('uploadArchives') { // dependency tasks are set dynamically via afterEvaluate
    doFirst {
        println "Upload artifacts for version $version"
    }
}


// fixed issue with libraries containing both .java and .class files
tasks.withType(JavaCompile) {
    options.sourcepath=files()
    options.encoding='UTF-8'
    options.incremental = true
}
tasks.withType(Javadoc) {
    options.addStringOption("sourcepath", "")
    if (JavaVersion.current().isJava8Compatible()) {
        options.addStringOption("Xdoclint:none", "-quiet")
        options.addBooleanOption("-allow-script-in-comments",true);
    }
    doLast {
        def searchScript = new File(destinationDir.getAbsolutePath() + '/search.js')
        searchScript.append "getURLPrefix = function(ui) { return ''; };"
    }
}
// all tasks implementing the CopySpec (Copy,Jar,Zip,...) should fail, in case they generate duplicate files
tasks.withType(CopySpec) {
    duplicatesStrategy 'fail'
}


// The Gradle module metadata generation ignores the non-transitiveness of our dependencies, just as the POM generation normally does.
// This leads to conflicts / build errors in dependent projects.
// We already manually fix it for the POM, but I don't know how to fix it for the module metadata generation.
// So just disable the module metadata - there is no benefit from it right now.
tasks.withType(GenerateModuleMetadata) {
    enabled = false
}


afterEvaluate {
	def uploadArchivesDeps = [tasks.findByName("publishToSonatype"), tasks.findByName("closeSonatypeStagingRepository")]
	tasks.findByName("uploadArchives").dependsOn(uploadArchivesDeps) 
}